
name: Demo workflow
on:
  push:
    branches:
      - summary

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
      - name: Read file contents
        run: |
          file_contents=$(cat data.txt)
          echo "file_contents=$file_contents" >> $GITHUB_ENV